name: Remove All Scoreboards
version: 0.1
main: de.magentaplugins.ras.ras
api-version: 1.20
authors: [MagentaGaming]
website: https://github.com/MagentaCoding/RAS
commands:
  ras:
    description: Entfernt alle Scoreboards (erneut tippen innerhalb 5 Sekunden zur Bestätigung)
  raswhitelist:
    description: Whitelist für Scoreboards bearbeiten (add/remove/list)

database: false
load: STARTUP